COLOR_FONDO = "#F0F2F5"
COLOR_FONDO_SECUNDARIO = "#FFFFFF"
COLOR_BARRA_LATERAL = "#E4E6EB"
COLOR_PRIMARIO = "#0084FF"
COLOR_PRIMARIO_ACTIVO = "#0062CC"
COLOR_TEXTO = "#050505"
COLOR_TEXTO_SECUNDARIO = "#65676B"
COLOR_MI_BURBUJA = "#0084FF"
COLOR_TEXTO_MI_MENSAJE = "#FFFFFF"

FONT_NORMAL = ("Segoe UI", 10)
FONT_BOLD = ("Segoe UI", 10, "bold")
FONT_ITALIC_PEQUEÑA = ("Segoe UI", 8, "italic")
FONT_TITULO = ("Segoe UI", 12, "bold")
FONT_TU = ("Segoe UI", 8, "normal")
